### ISSUE TITLE
SHOW WHICH GROQ LLM IS USED AND HOW CAN I CHOOSE MYSELF WHICH GROQ LLM IS USED?

### ISSUE THREAD

**Issue by jbdatascience** [jgravelle/pocketgroq#1]
Very usefull !

I have a question: in the examples on https://github.com/jgravelle/pocketgroq (and on https://pypi.org/project/pocketgroq/) is is not clear to me which exact Groq LLM model is used. The examples work beatifully, but how can I explicitly see what is the name of the Groq LLM? 

And how can I choose myself which Groq LLM is used?

**Comment by jgravelle** [comment]
Great observation.  We've fixed that with:
pocketgroq>=0.1.5

![image](https://github.com/user-attachments/assets/c49cec2d-78d9-47b2-9051-3e6b71b7fee9)

**Comment by jbdatascience** [comment]
Now it works as expected !
