### ISSUE TITLE
Example of tool use throws an error

### ISSUE THREAD

**Issue by jbdatascience** [jgravelle/pocketgroq#2]
Example of tool use throws an error.

This is the code I used from your examples:

`from pocketgroq import GroqProvider

def get_weather(location: str):
    # Simulated weather function
    return {"temperature": 20, "condition": "sunny"}

groq = GroqProvider()

tools = [
    {
        "type": "function",
        "function": {
            "name": "get_weather",
            "description": "Get the current weather for a location",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The city and state, e.g. San Francisco, CA",
                    }
                },
                "required": ["location"],
            },
            "implementation": get_weather
        }
    }
]

response = groq.generate("What's the weather in San Francisco?", tools=tools)
print(response)`

THIS IS THE ERROR THAT IS THROWN WHEN EXECUTING ABOVE CODE :

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pocketgroq/groq_provider.py](https://localhost:8080/#) in _sync_create_completion(self, **kwargs)
     68         try:
---> 69             response = self.client.chat.completions.create(**kwargs)
     70             if kwargs.get("stream", False):

16 frames
TypeError: Object of type function is not JSON serializable

During handling of the above exception, another exception occurred:

GroqAPIError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pocketgroq/groq_provider.py](https://localhost:8080/#) in _sync_create_completion(self, **kwargs)
     73                 return self._process_tool_calls(response, kwargs.get("tools"))
     74         except Exception as e:
---> 75             raise GroqAPIError(f"Error in Groq API call: {str(e)}")
     76 
     77     async def _async_create_completion(self, **kwargs) -> Union[str, AsyncIterator[str]]:

GroqAPIError: Error in Groq API call: Object of type function is not JSON serializable

Perhaps this to do with the particular kind of Groq LLM model that is used in the example? (Perhaps it is not equiped for tool use).

**Comment by jgravelle** [comment]
Try 'er now:

pocketgroq>=0.1.5

**Comment by jbdatascience** [comment]
Now it works as expected !
