### ISSUE TITLE
Error when I try to use tool (test.py, 8. Tool Usage)

### ISSUE THREAD

**Issue by jbdatascience** [jgravelle/pocketgroq#3]
I get an error when I try to do tool use.

It also shows when I run test.py, item 8:
8. Tool Usage

This is the error that I get:

"Enter your choice (0-13): 8

Testing Tool Usage...
DEBUG:groq._base_client:Request options: {'method': 'post', 'url': '/openai/v1/chat/completions', 'files': None, 'json_data': {'messages': [{'role': 'user', 'content': "Please reverse the string 'hello world'"}], 'model': 'llama3-groq-70b-8192-tool-use-preview', 'max_tokens': 1024, 'stop': None, 'stream': False, 'temperature': 0.5, 'tool_choice': 'auto', 'tools': [{'type': 'function', 'function': {'name': 'reverse_string', 'description': 'Reverse the given string', 'parameters': {'type': 'object', 'properties': {'input_string': {'type': 'string', 'description': 'The string to be reversed'}}, 'required': ['input_string']}, 'implementation': <function test_tool_usage.<locals>.reverse_string at 0x7e91d5c4eb00>}}], 'top_p': 1}}
API Error: Error in Groq API call: Object of type function is not JSON serializable"

What can be the cause of that?

**Comment by jgravelle** [comment]
Try a different model.  Some aren't JSON friendly without additional
prompting...


-jjg

**Comment by jbdatascience** [comment]
I will try that out more extensively ! I will let you know which Groq model works!

**Comment by danljensen** [comment]
This doesn't look like it's happening in model-specific code. The error is happening when it's trying to format the API request to send to Groq. Here's a stack trace of where it happens:

(Pdb) bt
  /home/daniel/pocketgroq/test.py(324)<module>()
-> asyncio.run(main())
  /usr/lib/python3.10/asyncio/runners.py(44)run()
-> return loop.run_until_complete(main)
  /usr/lib/python3.10/asyncio/base_events.py(636)run_until_complete()
-> self.run_forever()
  /usr/lib/python3.10/asyncio/base_events.py(603)run_forever()
-> self._run_once()
  /usr/lib/python3.10/asyncio/base_events.py(1909)_run_once()
-> handle._run()
  /usr/lib/python3.10/asyncio/events.py(80)_run()
-> self._context.run(self._callback, *self._args)
  /home/daniel/pocketgroq/test.py(289)main()
-> test_tool_usage()
  /home/daniel/pocketgroq/test.py(198)test_tool_usage()
-> response = groq.generate("Please reverse the string 'hello world'", tools=tools)
  /home/daniel/pocketgroq/pocketgroq/groq_provider.py(30)generate()
-> return self._create_completion(messages, **kwargs)
  /home/daniel/pocketgroq/pocketgroq/groq_provider.py(58)_create_completion()
-> return self._sync_create_completion(**completion_kwargs)
  /home/daniel/pocketgroq/pocketgroq/groq_provider.py(70)_sync_create_completion()
-> response = self.client.chat.completions.create(**kwargs)
  /home/daniel/.local/lib/python3.10/site-packages/groq/resources/chat/completions.py(283)create()
-> return self._post(
  /home/daniel/.local/lib/python3.10/site-packages/groq/_base_client.py(1225)post()
-> return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  /home/daniel/.local/lib/python3.10/site-packages/groq/_base_client.py(920)request()
-> return self._request(
  /home/daniel/.local/lib/python3.10/site-packages/groq/_base_client.py(941)_request()
-> request = self._build_request(options)
  /home/daniel/.local/lib/python3.10/site-packages/groq/_base_client.py(483)_build_request()
-> return self._client.build_request(  # pyright: ignore[reportUnknownMemberType]
  /home/daniel/.local/lib/python3.10/site-packages/httpx/_client.py(357)build_request()
-> return Request(
  /home/daniel/.local/lib/python3.10/site-packages/httpx/_models.py(340)__init__()
-> headers, stream = encode_request(
  /home/daniel/.local/lib/python3.10/site-packages/httpx/_content.py(212)encode_request()
-> return encode_json(json)
  /home/daniel/.local/lib/python3.10/site-packages/httpx/_content.py(175)encode_json()
-> body = json_dumps(json).encode("utf-8")
  /usr/lib/python3.10/json/__init__.py(231)dumps()
-> return _default_encoder.encode(obj)
  /usr/lib/python3.10/json/encoder.py(199)encode()
-> chunks = self.iterencode(o, _one_shot=True)
  /usr/lib/python3.10/json/encoder.py(257)iterencode()
-> return _iterencode(o, 0)
> /usr/lib/python3.10/json/encoder.py(179)default()
-> raise TypeError(f'Object of type {o.__class__.__name__} '

**Comment by jgravelle** [comment]
Looks like you're running python 3.10?  Might want to try 3.11.  And maybe give this alternate tool test a try:

python
````
def test_tool_usage():
    print("\nTesting Tool Usage...")
    def reverse_string(input_string: str) -> dict:
        return {"reversed_string": input_string[::-1]}

    tools = [
        {
            "type": "function",
            "function": {
                "name": "reverse_string",
                "description": "Reverse the given string",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "input_string": {
                            "type": "string",
                            "description": "The string to be reversed",
                        }
                    },
                    "required": ["input_string"],
                },
                "implementation": reverse_string
            }
        }
    ]

    groq = GroqProvider()
    prepared_tools = groq._prepare_tools(tools)
    print("Prepared tools:", json.dumps(prepared_tools, indent=2))

    response = groq.generate("Please reverse the string 'hello world'", tools=tools)
    print("Response:", response)
    assert "dlrow olleh" in response.lower()
    ```

**Comment by danljensen** [comment]
With your updated test, I'm getting the error:

Unexpected error: 'GroqProvider' object has no attribute '_prepare_tools'

Where is the _prepare_tools method supposed to be defined? Could that be in a commit you haven't pushed yet? Will try updating to Python 3.11 when I have more time.

**Comment by jgravelle** [comment]
Sorry.  I was doing two things at once.  Should have sent you this, too:

python

```
# pocketgroq/groq_provider.py

import os
import json
from typing import Dict, Any, List, Union, AsyncIterator
import asyncio

from groq import Groq, AsyncGroq
from .exceptions import GroqAPIKeyMissingError, GroqAPIError
from .web_tool import WebTool
from .chain_of_thought.cot_manager import ChainOfThoughtManager
from .chain_of_thought.llm_interface import LLMInterface

class GroqProvider(LLMInterface):
    # ... (previous code remains the same)

    def _create_completion(self, messages: List[Dict[str, str]], **kwargs)
-> Union[str, AsyncIterator[str]]:
        completion_kwargs = {
            "model": self._select_model(kwargs.get("model"),
kwargs.get("tools")),
            "messages": messages,
            "temperature": kwargs.get("temperature", 0.5),
            "max_tokens": kwargs.get("max_tokens", 1024),
            "top_p": kwargs.get("top_p", 1),
            "stop": kwargs.get("stop", None),
            "stream": kwargs.get("stream", False),
        }

        if kwargs.get("json_mode", False):
            completion_kwargs["response_format"] = {"type": "json_object"}

        if kwargs.get("tools"):
            completion_kwargs["tools"] =
self._prepare_tools(kwargs["tools"])
            completion_kwargs["tool_choice"] = kwargs.get("tool_choice",
"auto")

        if kwargs.get("async_mode", False):
            return self._async_create_completion(**completion_kwargs)
        else:
            return self._sync_create_completion(**completion_kwargs)

    def _prepare_tools(self, tools: List[Dict[str, Any]]) -> List[Dict[str,
Any]]:
        prepared_tools = []
        for tool in tools:
            prepared_tool = tool.copy()
            if 'function' in prepared_tool:
                prepared_function = prepared_tool['function'].copy()
                prepared_function.pop('implementation', None)
                prepared_tool['function'] = prepared_function
            prepared_tools.append(prepared_tool)
        return prepared_tools

    # ... (rest of the class remains the same)
```

**Comment by danljensen** [comment]
It's still not working. Looks like the issue is that _execute_tool_calls() can only deal with tools named "web_search" or "get_web_content". If it finds any other name, it sends an "Unknown tool" error back to the model. Presumably, the way to fix it would be for that function to be able to look up the implementation that was included in the tool definition when _prepare_tools() was called. Were you intending to save that off somewhere at the time that you popped it?

**Comment by jgravelle** [comment]
I know "works for me" is an unsatisfactory answer, so I won't offer it.

I pushed a new update last night adding RAG features.  Might wanna pull the new version...

**Comment by danljensen** [comment]
Your latest version seems to work, thanks. And it looks like _execute_tool_calls() is no longer restricted to working with a predetermined list of tool names, which would explain the difference. I am getting some test output regarding multiple definitions of the tool function, though. Not sure if that's expected?

`DEBUG:groq._base_client:HTTP Response: POST https://api.groq.com/openai/v1/chat/completions "200 OK" Headers({'date': 'Sat, 28 Sep 2024 15:07:05 GMT', 'content-type': 'application/json', 'transfer-encoding': 'chunked', 'connection': 'keep-alive', 'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate', 'vary': 'Origin', 'x-ratelimit-limit-requests': '14400', 'x-ratelimit-limit-tokens': '30000', 'x-ratelimit-remaining-requests': '14399', 'x-ratelimit-remaining-tokens': '29969', 'x-ratelimit-reset-requests': '6s', 'x-ratelimit-reset-tokens': '62ms', 'x-request-id': 'req_01j8wjqkrsev29txbf3a9g7ggy', 'via': '1.1 google', 'cf-cache-status': 'DYNAMIC', 'server': 'cloudflare', 'cf-ray': '8ca4a41e6ee42f4d-LAX', 'content-encoding': 'gzip'})
Response: It seems that both tool calls "call_j2er" and "call_zwmy" are actually referring to the same tool function, which is the "reverse_string" function. This function takes a string as input and returns the reversed string.

In this case, both tool calls with the same input "hello world" produce the same output "dlrow olleh".
`
