### ISSUE TITLE
Hi im having issues with running pocketqroq 

### ISSUE THREAD

**Issue by Digiguy1** [jgravelle/pocketgroq#4]
i installed it correctly 

<img width="755" alt="Screen Shot 2024-09-27 at 1 03 44 AM" src="https://github.com/user-attachments/assets/e17d6990-09b0-4480-86f7-78f6d9559cd9">

but every-time i try to use it i get this 
groq 
-bash: groq: command not found

**Comment by jgravelle** [comment]
# PocketGroq CLI Usage Guide

PocketGroq is not designed as a command-line tool that you can invoke directly with a `groq` command. Instead, it's a Python library that you import and use within your Python scripts or interactive sessions. Here's how to use PocketGroq correctly:

1. First, make sure you have PocketGroq installed:
   ```
   pip install pocketgroq
   ```

2. In your Python script or interactive session, import and use PocketGroq like this:
   ```python
   from pocketgroq import GroqProvider
   
   # Initialize the GroqProvider
   groq = GroqProvider()
   
   # Use PocketGroq functionalities
   response = groq.generate("Your prompt here")
   print(response)
   ```

3. Remember to set your GROQ_API_KEY environment variable or pass it directly to the GroqProvider constructor:
   ```python
   groq = GroqProvider(api_key="your-api-key-here")
   ```

If you need command-line functionality, you'll need to create a script that uses PocketGroq and can be run from the command line. Here's a simple example:

```python
#!/usr/bin/env python3
import sys
from pocketgroq import GroqProvider

def main():
    if len(sys.argv) < 2:
        print("Usage: python groq_cli.py 'Your prompt here'")
        sys.exit(1)
    
    groq = GroqProvider()
    prompt = sys.argv[1]
    response = groq.generate(prompt)
    print(response)

if __name__ == "__main__":
    main()
```

Save this as `groq_cli.py`, make it executable (`chmod +x groq_cli.py`), and you can use it like this:

```
./groq_cli.py "Your prompt here"
```

For more detailed usage and advanced features, please refer to the PocketGroq documentation.

**Comment by Digiguy1** [comment]
Thanks

**Comment by Digiguy1** [comment]
@jgravelle hi i created a .env file as the environment variable in the root folder of pocketgroq but that dont seem to work 
where should i put the api key 

this the error i get 
/pocketgroq/pocketgroq/groq_provider.py", line 27, in __init__
    raise GroqAPIKeyMissingError("Groq API key is not provided")
pocketgroq.exceptions.GroqAPIKeyMissingError: Groq API key is not provided

**Comment by jgravelle** [comment]
Your best bet is to make it an environment variable...
[https://console.groq.com/docs/quickstart](https://console.groq.com/docs/quickstart)
