### ISSUE TITLE
No chain_of_thought module

### ISSUE THREAD

**Issue by williamj77** [jgravelle/pocketgroq#5]
Hello,

I get this error when attempting to run from a script on a Windows machine.

ModuleNotFoundError: No module named 'pocketgroq.chain_of_thought'

I did install pocketgroq and activated via conda.

williamj

**Comment by jgravelle** [comment]
Can we see the script...?

**Comment by williamj77** [comment]
The script is the same except for the host names.

**Comment by jgravelle** [comment]
The same as WHAT though...?


-jjg

**Comment by williamj77** [comment]
Hello,

I am using your sample project.

williamj

**Comment by jgravelle** [comment]
I'm not finding a sample project, boss:

https://github.com/jgravelle/pocketgroq

If I can get the specifics on what you're doing, I might be more help...


-jjg

**Comment by ruudzon** [comment]
> Hello,
> 
> I get this error when attempting to run from a script on a Windows machine.
> 
> ModuleNotFoundError: No module named 'pocketgroq.chain_of_thought'
> 
> I did install pocketgroq and activated via conda.
> 
> williamj

Is it possible that there is a typo? maybe you can check with : conda info --envs

**Comment by williamj77** [comment]
Hello,

I’m sorry.

I am using the same script from croqcasters.

But I did pip install pocketcroq with the error on the missing module still occurring.

williamj

**Comment by jgravelle** [comment]
Try this...

- git clone https://github.com/yourusername/groqcasters.git
- cd groqcasters
- conda create -n groqcasters python=3.11
- conda activate groqcasters
- pip install -r requirements.txt
- pip install pocketgroq
- python groqcasters.py path/to/input_text.txt path/to/output_directory  [
*Be sure to configure an actual path to existing input_text.txt and a valid
output_directory, preferably empty ]
...or...
- python groqcasters.py path/to/script.txt path/to/output_directory
--use-script [ *Again, making certain the script and target directories
exist. ]


-jjg

**Comment by williamj77** [comment]
Hello,

I did.

But I am using Anaconda Navigator.

williamj

**Comment by jgravelle** [comment]
PocketGroq Incorporated is proud to announce the promotion of WilliamJ77 to head of research for our new Anaconda Navigator testing division.  We're excited to have him on board and look forward to him sharing his discoveries with us.  Congratulations...!

**Comment by williamj77** [comment]
Hello,

Have you made any progress?

I don’t know why the module is missing.

williamj

**Comment by williamj77** [comment]
Hello,

I received this error when following your instructions:

williamj

**Comment by jgravelle** [comment]
Try installing by following the instructions on GitHub rather than doing a
pip install:

https://github.com/jgravelle/pocketgroq


-jjg
