### ISSUE TITLE
Any specific way of getting the scrape to work on a captcha ?

### ISSUE THREAD

**Issue by makapaka23** [jgravelle/pocketgroq#6]
Maybe I'm not seeing something but can anyone provide examples or help on a site that might or might not be using captcha?

A basic "scrape_url()" is giving me a 403 err

**Comment by jgravelle** [comment]
That may or may not be a Captcha issue.  If it is, no, I don't have a current workaround.  

Other things that can cause it:  

- Streamlit's IPs are blocked from a lot of sites.  You may find quite a few that work locally but not when hosted.
- Choice of model.  Some don't play nice with the web tools.
- Bad juju.  I sell talismans for this on Etsy...
